### ISSUE TITLE
项目无法构建

### ISSUE THREAD

**Issue by fenggit** [ccj659/clean-project-architecture#1]
Error:(2, 0) Cause: com/dodola/rocoofix/RocooFixPlugin : Unsupported major.minor version 52.0
<a href="openFile:D:\git\clean-project-architecture-master\app\build.gradle">Open File</a>

请问这是怎么回事？

**Comment by ccj659** [comment]
原因:
1.热修复框架在兼容gradle版本目前只能到2.1.2.
2.java -version看一下你运行的jvm是什么版本的jdk，然后在你的android studio里面把jdk改成对应的版本重新compile

如果还不行,请去掉热修复相关,然后重新build.

**Comment by fenggit** [comment]
好的，谢谢
