### ISSUE TITLE
使用ARouter获取Fragment返回null

### ISSUE THREAD

**Issue by Eason2Wang** [ccj659/clean-project-architecture#3]
Fragment home = (Fragment) ARouter.getInstance().build(RouterConstants.HOME_MUDULE_FRAGMENT_HOME_HOME).navigation();返回为null。

**Comment by ccj659** [comment]
gradle.properties文件中 isModule属性 true代表模块开发,false代表合并到主app.
 
isModule=true

找不到目的地,是因为现在是模块开发,改为false即可运行主app.
